//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client Microsoft SQL Server backed Proxy/Service Ticket Managers")]
[assembly: AssemblyDescription("Microsoft SQL Server backed Proxy/Service Ticket Managers for the Apereo .NET CAS Client.")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client Microsoft SQL Server backed Proxy/Service Ticket Managers")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-unstable.5+Branch.develop.Sha.a4775eebef1ec4523261c4bf2d7636ccb339d800")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2018 Apereo.  All rights reserved.")]

